CUSTOM_FIELD = {
    "Employee":[
        {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_employee_code",
            "fieldtype": "Data",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "naming_series",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Employee Code",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_employee_code",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 1,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_consultant_",
            "fieldtype": "Select",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "employee_number",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Consultant ",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_consultant_",
            "no_copy": 0,
            "non_negative": 0,
            "options": "\nDirect",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 1,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_designation_visa",
            "fieldtype": "Link",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "designation",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Designation Visa",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_designation_visa",
            "no_copy": 0,
            "non_negative": 0,
            "options": "Designation",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_nationality",
            "fieldtype": "Link",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_designation_visa",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Nationality",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_nationality",
            "no_copy": 0,
            "non_negative": 0,
            "options": "Country",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_passport_number_new",
            "fieldtype": "Data",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "passport_number",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Passport Number New",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_passport_number_new",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 1,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_days_left_passport",
            "fieldtype": "Int",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "column_break_73",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Days Left Passport",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_days_left_passport",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_passport_status",
            "fieldtype": "Select",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_days_left_passport",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Passport Status",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_passport_status",
            "no_copy": 0,
            "non_negative": 0,
            "options": "\nw/company\nw/employee",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 1,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_emirates_details",
            "fieldtype": "Section Break",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "place_of_issue",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Emirates Details",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_emirates_details",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_emirates_id",
            "fieldtype": "Data",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_emirates_details",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Emirates Id",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_emirates_id",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 1,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_emirates_id_expiry_date",
            "fieldtype": "Date",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_emirates_id",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Emirates Id Expiry Date",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_emirates_id_expiry_date",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_emirated_id_expiry_days",
            "fieldtype": "Data",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_emirates_id_expiry_date",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Emirated Id Expiry Days",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_emirated_id_expiry_days",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 1,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_uid_number",
            "fieldtype": "Data",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_emirated_id_expiry_days",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "UID Number",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_uid_number",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 1,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_e_visa_number",
            "fieldtype": "Data",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_uid_number",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "E Visa Number",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_e_visa_number",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 1,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_personal_id",
            "fieldtype": "Data",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_e_visa_number",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Personal Id",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_personal_id",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 1,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_column_break_oqgbz",
            "fieldtype": "Column Break",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_personal_id",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_column_break_oqgbz",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_labour_card",
            "fieldtype": "Data",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_column_break_oqgbz",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Labour Card",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_labour_card",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 1,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_labour_card_expiry",
            "fieldtype": "Date",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_labour_card",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Labour Card Expiry",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_labour_card_expiry",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 1,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_current_visa_status",
            "fieldtype": "Select",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_labour_card_expiry",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Current Visa Status",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_current_visa_status",
            "no_copy": 0,
            "non_negative": 0,
            "options": "\nExisting",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 1,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_orient_card_number",
            "fieldtype": "Data",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_current_visa_status",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Orient Card Number",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_orient_card_number",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 1,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_working_status",
            "fieldtype": "Select",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_orient_card_number",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Working Status",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_working_status",
            "no_copy": 0,
            "non_negative": 0,
            "options": "\nWorking\nVacation",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 1,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_c3_card_number",
            "fieldtype": "Data",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_working_status",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "C3 Card Number",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_c3_card_number",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 1,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_ticket_allowance",
            "fieldtype": "Section Break",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "default_shift",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Ticket Allowance",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_ticket_allowance",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_add_ticket_allowance",
            "fieldtype": "Button",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_ticket_allowance",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Add Ticket Allowance",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_add_ticket_allowance",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_ticket_allowance_due_in",
            "fieldtype": "Data",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_add_ticket_allowance",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Ticket Allowance Due In",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_ticket_allowance_due_in",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 1,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_column_break_8kyxq",
            "fieldtype": "Column Break",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_ticket_allowance_due_in",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_column_break_8kyxq",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": ""
            }, 
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_last_ticket_allowance_date",
            "fieldtype": "Date",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_column_break_8kyxq",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "Last Ticket Allowance Date",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_last_ticket_allowance_date",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 1,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": ""
            },
            {
            "allow_in_quick_entry": 0,
            "allow_on_submit": 0,
            "bold": 0,
            "collapsible": 0,
            "collapsible_depends_on": "",
            "columns": 0,
            "default": "",
            "depends_on": "",
            "description": "",
            "docstatus": 0,
            "doctype": "Custom Field",
            "dt": "Employee",
            "fetch_from": "",
            "fetch_if_empty": 0,
            "fieldname": "custom_view_history",
            "fieldtype": "Button",
            "hidden": 0,
            "hide_border": 0,
            "hide_days": 0,
            "hide_seconds": 0,
            "ignore_user_permissions": 0,
            "ignore_xss_filter": 0,
            "in_global_search": 0,
            "in_list_view": 0,
            "in_preview": 0,
            "in_standard_filter": 0,
            "insert_after": "custom_last_ticket_allowance_date",
            "is_system_generated": 0,
            "is_virtual": 0,
            "label": "View History",
            "length": 0,
            "mandatory_depends_on": "",
            "module": "",
            "name": "Employee-custom_view_history",
            "no_copy": 0,
            "non_negative": 0,
            "options": "",
            "permlevel": 0,
            "precision": "",
            "print_hide": 0,
            "print_hide_if_no_value": 0,
            "print_width": "",
            "read_only": 0,
            "read_only_depends_on": "",
            "report_hide": 0,
            "reqd": 0,
            "search_index": 0,
            "sort_options": 0,
            "translatable": 0,
            "unique": 0,
            "width": ""
            },
        ],
        "Salary Slip":[
            {
                "dt":"Salary Slip",
                "fieldname": "custom_overtime_details",
                "fieldtype": "Section Break",
                "label": "Overtime Details",
                "insert_after": "base_total_deduction",
                "read_only": 1,

            },
            {
                "dt":"Salary Slip",
                "fieldname": "custom_overtime_hours",
                "fieldtype": "Float",
                "label": "Overtime Hours",
                "insert_after": "custom_overtime_details",
                "read_only": 1,

            },
            {
                "dt":"Salary Slip",
                "fieldname": "custom_extra_hours",
                "fieldtype": "Float",
                "label": "Extra Hours",
                "insert_after": "custom_overtime_hours",
                "read_only": 1,

            },
            {
                "dt":"Salary Slip",
                "fieldname": "custom_total_salary",
                "fieldtype": "Currency",
                "label": "Total Salary",
                "insert_after": "custom_overtime_hours",
                "read_only": 1,

            },
            {
                "dt":"Salary Slip",
                "fieldname": "custom_overtime_details",
                "fieldtype": "Column Break",
                "label": "Overtime Details",
                "insert_after": "custom_overtime_hours",
                "read_only": 1,

            },
            {
                "dt":"Salary Slip",
                "fieldname": "custom_overtime_amount",
                "fieldtype": "Currency",
                "label": "Overtime Amount",
                "insert_after": "custom_total_salary",
                "read_only": 1,

            },
            {
                "dt":"Salary Slip",
                "fieldname": "custom_extra_hour_amount",
                "fieldtype": "Currency",
                "label": "Extra Hour Amount",
                "insert_after": "custom_overtime_amount",
                "read_only": 1,

            },
        ],
    "Attendance":[
        {
            "dt":"Attendance",
            "fieldname": "custom_leave_type",
            "fieldtype": "Select",
            "label": "Leave Type",
            "insert_after": "status",
            "read_only": 1,
            "options":"\nMedical\nSick\nLeave"

        },
        {
            "dt":"Attendance",
            "fieldname": "custom_reference_labour_attendance_and_overtime",
            "fieldtype": "Link",
            "label": "Reference Labour Attendance And Overtime",
            "insert_after": "company",
            "read_only": 1,
            "options":"Labour Attendance And Overtime"

        },
    ]
    }